### ISSUE TITLE
Error when using Embed with XLSX data

### ISSUE THREAD

**Issue by CovertDad** [andymeneely/squib#143]
If I try to use the embed command with a fixed amount of cards, everything works fine.  If I try to use a linked XLSX file for my data, it blows up.

I copied a bit from the sample to make sure it wasn't something else I was doing wrong.

This works:

```ruby
require 'squib'
Squib::Deck.new(cards: 3) do
  str = 'Take 1 :tool: and gain 2 :health:.'
  text(str: str, font: 'Sans', font_size: [18, 26, 35],
       x: 0, y: 0, width: 180, height: 300, valign: :bottom,
       align: :left, ellipsize: false, justify: false, hint: :cyan) do |embed|
    embed.svg key: ':tool:',   width: [28, 42, 56], height: [28, 42, 56], file: 'images/cubes-blue.svg'
    embed.svg key: ':health:', width: [28, 42, 56], height: [28, 42, 56], file: 'images/cubes-red.svg'
  end
  save_sheet prefix: 'embed_multisheet_', columns: 3
end
```

This produces an error:
```ruby
require 'squib'

data = Squib.xlsx file:'Cards.xlsx'
num_cards = data['Name'].size    

Squib::Deck.new(cards: num_cards) do
  str = 'Take 1 :tool: and gain 2 :health:.'
  text(str: str, font: 'Sans', font_size: [18, 26, 35],
       x: 0, y: 0, width: 180, height: 300, valign: :bottom,
       align: :left, ellipsize: false, justify: false, hint: :cyan) do |embed|
    embed.svg key: ':tool:',   width: [28, 42, 56], height: [28, 42, 56], file: 'images/cubes-blue.svg'
    embed.svg key: ':health:', width: [28, 42, 56], height: [28, 42, 56], file: 'images/cubes-red.svg'
  end
  save_sheet prefix: 'embed_multisheet_', columns: 3
end
```

Specifically, the error is:
```
/Library/Ruby/Gems/2.0.0/gems/squib-0.9.0/lib/squib/graphics/text.rb:88:in `process_embeds': undefined method `*' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/squib-0.9.0/lib/squib/graphics/text.rb:149:in `block in text'
	from /Library/Ruby/Gems/2.0.0/gems/squib-0.9.0/lib/squib/card.rb:50:in `yield'
	from /Library/Ruby/Gems/2.0.0/gems/squib-0.9.0/lib/squib/card.rb:50:in `use_cairo'
	from /Library/Ruby/Gems/2.0.0/gems/squib-0.9.0/lib/squib/graphics/text.rb:124:in `text'
	from /Library/Ruby/Gems/2.0.0/gems/squib-0.9.0/lib/squib/api/text.rb:60:in `block in text'
	from /Library/Ruby/Gems/2.0.0/gems/squib-0.9.0/lib/squib/args/card_range.rb:13:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/squib-0.9.0/lib/squib/args/card_range.rb:13:in `block in each'
	from /Library/Ruby/Gems/2.0.0/gems/squib-0.9.0/lib/squib/args/card_range.rb:13:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/squib-0.9.0/lib/squib/args/card_range.rb:13:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/squib-0.9.0/lib/squib/api/text.rb:60:in `text'
	from deck.rb:29:in `block in <main>'
	from /Library/Ruby/Gems/2.0.0/gems/squib-0.9.0/lib/squib/deck.rb:73:in `instance_eval'
	from /Library/Ruby/Gems/2.0.0/gems/squib-0.9.0/lib/squib/deck.rb:73:in `initialize'
	from deck.rb:27:in `new'
	from deck.rb:27:in `<main>'
```

**Comment by andymeneely** [comment]
Based on that error I don't think it's the `xlsx` method that's the problem - its seems to be failing with the text embeds. But I don't see a problem between the two? When I run the second piece of code I don't get that error.

(by the way, if you do ```ruby you'll get syntax highlighting: https://guides.github.com/features/mastering-markdown/)

**Comment by CovertDad** [comment]
Checking the code, this is the line it's erroring on:

```ruby
spacing = rule[:box].width[@index] * Pango::SCALE
```

It doesn't seem to like that asterisk if it's doing a dynamic amount of cards.  If I simply change the cards parameter from num_cards to 3, it works fine.

**Comment by andymeneely** [comment]
Maybe your data isn't getting parsed the way you think it should. put in a `puts data` and see if it looks right.

**Comment by andymeneely** [comment]
Oh I think I know what's going on. num_cards is much bigger than 3, right? That would mean that `nil` is getting passed to width and height. Because this:

```
$ irb
irb(main):001:0> arr = [1,2,3]
=> [1, 2, 3]
irb(main):002:0> arr[56]
=> nil
```

And Squib doesn't like that. To be fair, Squib should tell you up front that it doesn't like `width: nil` instead of failing deep within its logic.

**Comment by andymeneely** [comment]
I'll get some better nil checks on those fields in particular.

**Comment by CovertDad** [comment]
Yes, that was the problem, which I realized about 30 seconds before you posted it.  :-)

Now I just have to figure out how to reuse embed code.
