### ISSUE TITLE
Update deprecated paragraph characters

### ISSUE THREAD

**Issue by daveschaefer** [andymeneely/squib#227]
Hello, thanks for making Squib! It looks great :)

I'm running ruby 2.3.3p222 on Windows 7. When I run squib to create one of the example decks I get errors like this:

```
C:/Ruby23/lib/ruby/gems/2.3.0/gems/squib-0.13.2/lib/squib/args/paragraph.rb:52:in `validate_align':
  'Pango::ALIGN_LEFT' has been deprecated. Use 'Pango::Alignment::LEFT' or ':left'.

C:/Ruby23/lib/ruby/gems/2.3.0/gems/squib-0.13.2/lib/squib/args/paragraph.rb:69:in `validate_wrap':
 'Pango::Layout::WRAP_WORD_CHAR' has been deprecated. Use 'Pango::WrapMode::WORD_CHAR' or ':word_char'.

C:/Ruby23/lib/ruby/gems/2.3.0/gems/squib-0.13.2/lib/squib/args/paragraph.rb:84:in `validate_ellipsize': 
'Pango::Layout::ELLIPSIZE_END' has been deprecated. Use'Pango::EllipsizeMode::END' or ':end'.
```

Would you be interested in a small patch to update the characters and remove these messages? Or is that not really a concern?

Thanks for your time!

**Comment by andymeneely** [comment]
Yeah it's not a concern. I'll fix it for the next update.

**Comment by andymeneely** [comment]
This has been done.
