### ISSUE TITLE
installations problems

### ISSUE THREAD

**Issue by peterusev** [andymeneely/squib#263]
Hi all,

Having some issues when trying to get the gem installed.
I'm using ruby 2.6.1p33 with rbenv / mojave 10.14.3 / all of cairo, pango, nokogiri already installed. Have spent a fair bit of time trying different things to fix the problem with no luck. Below are the errors I'm seeing -- any thoughts on how I might resolve this?

`Building native extensions. This could take a while...
ERROR:  Error installing squib:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/cairo-1.15.13/ext/cairo
/usr/local/var/rbenv/versions/2.6.1/bin/ruby -I /usr/local/var/rbenv/versions/2.6.1/lib/ruby/2.6.0 -r ./siteconf20190309-81951-kt933y.rb extconf.rb
checking for GCC... yes
checking for Win32 OS... no
checking for cairo version (>= 1.2.0)... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/var/rbenv/versions/2.6.1/bin/$(RUBY_BASE_NAME)
	--with-pkg-config
	--without-pkg-config
	--with-override-variables
	--without-override-variables
/usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:319:in `parse_pc': .pc for libffi doesn't exist. (RuntimeError)
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:218:in `declaration'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:232:in `collect_cflags'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:167:in `cflags'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:234:in `block in collect_cflags'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:233:in `collect'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:233:in `collect_cflags'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:167:in `cflags'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:234:in `block in collect_cflags'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:233:in `collect'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:233:in `collect_cflags'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:176:in `cflags_only_other'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:488:in `cflags_only_other'
	from /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pkg-config-1.3.5/lib/pkg-config.rb:535:in `have_package'
	from extconf.rb:52:in `required_pkg_config_package'
	from extconf.rb:60:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-18/2.6.0-static/cairo-1.15.13/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/cairo-1.15.13 for inspection.
Results logged to /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-18/2.6.0-static/cairo-1.15.13/gem_make.out
`
and here is the log

`checking for GCC... -------------------- yes

"clang -o conftest -I/usr/local/var/rbenv/versions/2.6.1/include/ruby-2.6.0/x86_64-darwin18 -I/usr/local/var/rbenv/versions/2.6.1/include/ruby-2.6.0/ruby/backward -I/usr/local/var/rbenv/versions/2.6.1/include/ruby-2.6.0 -I. -I/usr/local/var/rbenv/versions/2.6.1/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/usr/local/var/rbenv/versions/2.6.1/lib -L. -L/usr/local/var/rbenv/versions/2.6.1/lib  -fstack-protector-strong -L/usr/local/lib     -lruby.2.6-static -framework Security -framework Foundation -lpthread -ldl -lobjc   "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"clang -I/usr/local/var/rbenv/versions/2.6.1/include/ruby-2.6.0/x86_64-darwin18 -I/usr/local/var/rbenv/versions/2.6.1/include/ruby-2.6.0/ruby/backward -I/usr/local/var/rbenv/versions/2.6.1/include/ruby-2.6.0 -I. -I/usr/local/var/rbenv/versions/2.6.1/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe   -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: /*top*/
4: #ifndef __GNUC__
5: # error
6: |:/ === __GNUC__ undefined === /:|
7: #endif
/* end */

--------------------

checking for Win32 OS... -------------------- no

--------------------

have_package: checking for cairo version (>= 1.2.0)... -------------------- yes

--------------------
`

**Comment by peterusev** [comment]
Looks like the following addition to my .bash_profile fixed the problem of not being able to install:
`export PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig`.
