### ISSUE TITLE
Backtrace when trying to embed svg in text

### ISSUE THREAD

**Issue by sadmac7000** [andymeneely/squib#285]
Executing the following:
```ruby
require 'squib'

data = Squib::csv file: 'jobs.csv'
num_cards = data['Workload'].size

Squib::Deck.new(cards: num_cards, layout: 'economy.yml') do
  background color: 'white'
  rect layout: 'cut'
  rect layout: 'safe'

  data_binary = data['Workload'].map do
    |x| x.to_s(2)
  end

  text( str: data_binary, layout: 'title') do |embed|
    embed.svg key: '1', file: 'red.svg'
    embed.svg key: '0', file: 'blue.svg'
  end

  save_pdf
end
```

Resulted in:

```
Traceback (most recent call last):
        18: from deck.rb:6:in `<main>'
        17: from deck.rb:6:in `new'
        16: from /usr/local/share/gems/gems/squib-0.15.0/lib/squib/deck.rb:74:in `initialize'
        15: from /usr/local/share/gems/gems/squib-0.15.0/lib/squib/deck.rb:74:in `instance_eval'
        14: from deck.rb:15:in `block in <main>'
        13: from /usr/local/share/gems/gems/squib-0.15.0/lib/squib/api/text.rb:20:in `text'
        12: from /usr/local/share/gems/gems/squib-0.15.0/lib/squib/args/card_range.rb:13:in `each'
        11: from /usr/local/share/gems/gems/squib-0.15.0/lib/squib/args/card_range.rb:13:in `each'
        10: from /usr/local/share/gems/gems/squib-0.15.0/lib/squib/args/card_range.rb:13:in `block in each'
         9: from /usr/local/share/gems/gems/squib-0.15.0/lib/squib/api/text.rb:20:in `block in text'
         8: from /usr/local/share/gems/gems/squib-0.15.0/lib/squib/graphics/text.rb:129:in `text'
         7: from /usr/local/share/gems/gems/squib-0.15.0/lib/squib/card.rb:51:in `use_cairo'
         6: from /usr/local/share/gems/gems/squib-0.15.0/lib/squib/graphics/text.rb:163:in `block in text'
         5: from /usr/share/ruby/forwardable.rb:230:in `show_pango_layout'
         4: from /usr/local/share/gems/gems/gobject-introspection-3.3.6/lib/gobject-introspection/loader.rb:533:in `block in define_method'
         3: from /usr/local/share/gems/gems/gobject-introspection-3.3.6/lib/gobject-introspection/loader.rb:614:in `invoke'
         2: from /usr/local/share/gems/gems/gobject-introspection-3.3.6/lib/gobject-introspection/loader.rb:614:in `invoke'
         1: from /usr/local/share/gems/gems/squib-0.15.0/lib/squib/graphics/text.rb:102:in `block in embed_images!'
/usr/local/share/gems/gems/squib-0.15.0/lib/squib/graphics/text.rb:29:in `compute_valign': undefined method `*' for :native:Symbol (NoMethodError)
```

**Comment by andymeneely** [comment]
Yeah I've been getting this more and more lately too. It seems to be happening more with Ruby 2.6 than Ruby 2.5. I'm looking into it. 

And from what I can tell, it's only on Windows. And it's intermittent for me, which is worse. 

It does reliably work on Linux, so my personal workaround is doing some builds inside Docker. But if you're not familiar with Docker that might be a bit of a learning curve. 

I'm going to see if I can narrow it down more and get the bug report to the library that this is failing in. I don't believe it's got anything to do with my code.

**Comment by jrogozen** [comment]
i'm getting something similar when trying to embed in text

here's my stacktrace. happening on mac os x for me.

```
GLib-GObject-CRITICAL **: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
	from /Users/jonro/.rvm/gems/ruby-2.6.3/gems/gobject-introspection-3.4.1/lib/gobject-introspection/loader.rb:272:in `block in load_field_writer'
	from /Users/jonro/.rvm/gems/ruby-2.6.3/gems/squib-0.15.3/lib/squib/graphics/text.rb:89:in `block (2 levels) in embed_images!'
	from /Users/jonro/.rvm/gems/ruby-2.6.3/gems/squib-0.15.3/lib/squib/graphics/text.rb:86:in `each'
	from /Users/jonro/.rvm/gems/ruby-2.6.3/gems/squib-0.15.3/lib/squib/graphics/text.rb:86:in `block in embed_images!'
	from /Users/jonro/.rvm/gems/ruby-2.6.3/gems/squib-0.15.3/lib/squib/graphics/text.rb:84:in `each'
	from /Users/jonro/.rvm/gems/ruby-2.6.3/gems/squib-0.15.3/lib/squib/graphics/text.rb:84:in `embed_images!'
	from /Users/jonro/.rvm/gems/ruby-2.6.3/gems/squib-0.15.3/lib/squib/graphics/text.rb:155:in `block in text'
	from /Users/jonro/.rvm/gems/ruby-2.6.3/gems/squib-0.15.3/lib/squib/card.rb:51:in `use_cairo'
	from /Users/jonro/.rvm/gems/ruby-2.6.3/gems/squib-0.15.3/lib/squib/graphics/text.rb:129:in `text'
	from /Users/jonro/.rvm/gems/ruby-2.6.3/gems/squib-0.15.3/lib/squib/api/text.rb:20:in `block in text'
	from /Users/jonro/.rvm/gems/ruby-2.6.3/gems/squib-0.15.3/lib/squib/args/card_range.rb:13:in `block in each'
	from /Users/jonro/.rvm/gems/ruby-2.6.3/gems/squib-0.15.3/lib/squib/args/card_range.rb:13:in `each'
	from /Users/jonro/.rvm/gems/ruby-2.6.3/gems/squib-0.15.3/lib/squib/args/card_range.rb:13:in `each'
	from /Users/jonro/.rvm/gems/ruby-2.6.3/gems/squib-0.15.3/lib/squib/api/text.rb:20:in `text'
	from /Users/jonro/code/decktool/card_maker/lib/marvel_champions/ally/ally.rb:51:in `block in create_image'
	from /Users/jonro/.rvm/gems/ruby-2.6.3/gems/squib-0.15.3/lib/squib/deck.rb:74:in `instance_eval'
	from /Users/jonro/.rvm/gems/ruby-2.6.3/gems/squib-0.15.3/lib/squib/deck.rb:74:in `initialize'
	from /Users/jonro/code/decktool/card_maker/lib/marvel_champions/ally/ally.rb:14:in `new'
	from /Users/jonro/code/decktool/card_maker/lib/marvel_champions/ally/ally.rb:14:in `create_image'
	from /Users/jonro/code/decktool/card_maker/app/controllers/index.rb:21:in `block in <top (required)>'
```

**Comment by jrogozen** [comment]
upgrading from ruby 2.6.3 -> ruby 2.7.0 fixed this for me

**Comment by andymeneely** [comment]
Oh interesting. Must have been something idiosyncratic about Ruby 2.6.
