### ISSUE TITLE
Error when all text would be replaced by embed

### ISSUE THREAD

**Issue by undercoverdesigns** [andymeneely/squib#307]
The fix for this issue seems to be causing problems for me.  When I attempt to create an embed with only text that will be replaced, I'm getting the following:

```
/usr/local/lib/ruby/gems/2.7.0/gems/squib-0.15.3/lib/squib/api/data.rb:42: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/csv.rb:679: warning: The called method 'parse' is defined here
/usr/local/lib/ruby/gems/2.7.0/gems/squib-0.15.3/lib/squib/graphics/text.rb:29:in 'compute_valign': undefined method '*' for :native:Symbol
	 from /usr/local/lib/ruby/gems/2.7.0/gems/squib-0.15.3/lib/squib/graphics/text.rb:102:in 'block in embed_images!'
	 from /usr/local/lib/ruby/gems/2.7.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:598:in 'invoke'
	 from /usr/local/lib/ruby/gems/2.7.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:598:in 'invoke'
	 from /usr/local/lib/ruby/gems/2.7.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:514:in 'block in define_method'
	 from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/forwardable.rb:235:in 'show_pango_layout'
	 from /usr/local/lib/ruby/gems/2.7.0/gems/squib-0.15.3/lib/squib/graphics/text.rb:163:in 'block in text'
	 from /usr/local/lib/ruby/gems/2.7.0/gems/squib-0.15.3/lib/squib/card.rb:51:in 'use_cairo'
	 from /usr/local/lib/ruby/gems/2.7.0/gems/squib-0.15.3/lib/squib/graphics/text.rb:129:in 'text'
	 from /usr/local/lib/ruby/gems/2.7.0/gems/squib-0.15.3/lib/squib/api/text.rb:20:in 'block in text'
	 from /usr/local/lib/ruby/gems/2.7.0/gems/squib-0.15.3/lib/squib/args/card_range.rb:13:in 'block in each'
	 from /usr/local/lib/ruby/gems/2.7.0/gems/squib-0.15.3/lib/squib/args/card_range.rb:13:in 'each'
	 from /usr/local/lib/ruby/gems/2.7.0/gems/squib-0.15.3/lib/squib/args/card_range.rb:13:in 'each'
	 from /usr/local/lib/ruby/gems/2.7.0/gems/squib-0.15.3/lib/squib/api/text.rb:20:in 'text'
	 from cards.rb:17:in 'block in <main>'
	 from /usr/local/lib/ruby/gems/2.7.0/gems/squib-0.15.3/lib/squib/deck.rb:74:in 'instance_eval'
	 from /usr/local/lib/ruby/gems/2.7.0/gems/squib-0.15.3/lib/squib/deck.rb:74:in 'initialize'
	 from cards.rb:5:in 'new'
	 from cards.rb:5:in '<main>'
```

My deck file is:

```
require 'squib'

data = Squib.csv file: 'data/cards.csv'

Squib::Deck.new(cards: data['title'].size, layout: 'layout.yml') do
  background color: 'white'
  rect layout: 'pos_1'
  rect layout: 'pos_2'
  rect layout: 'pos_3'
  rect layout: 'pos_4'
  rect layout: 'pos_5'
  rect layout: 'pos_6'
  rect layout: 'pos_7'
  rect layout: 'pos_8'

  text(str: data['pos_1'], layout: 'pos_1', align: :right, valign: :middle) do |embed|
    embed.svg key: '[V]', file: 'image/viking-head.svg'
  end
  
  save_pdf sprue: 'ccg.yml', prefix: "cards_"
end
```

The first two rows of my CSV:
```
random,title,pos_1,pos_2,pos_3,pos_4,pos_5,pos_6,pos_7,pos_8,position,action_row,resolution_direction_1,resolution_direction_2
0.4759180054,Card 1,[V][V],[V][V],[V][V],[V][V],[V][V][V],[V][V][V][V],[V][V],[V][V],4,build,Up,Right
```

When I add a non-space character between instances of '[V]' in my text, it works as expected.

The line that is generating the error was fixed in #134.

**Comment by andymeneely** [comment]
@undercoverdesigns did you mean to close the issue? is it still a problem?

**Comment by undercoverdesigns** [comment]
@andymeneely Yes, I meant to close it.  After I posted it, I did something (can't remember off the top of my head) that made the error go away.
