### ISSUE TITLE
Does this work on your machine only?

### ISSUE THREAD

**Issue by mercenaryntx** [andymeneely/squib#324]
It's really great to see that such project exists. 

However, I know nothing about Ruby development and I'd like to keep it that way. I just want to see this to run on my machine and I don't really get why is it so damn difficult. Did you develop this tool for rocket scientists, guys wearing socks with sandals or something?! 

To be honest I don't really like to infect my machine with obscure devkits so I first tried to install it on my WSL2 (Ubuntu 20.04). It failed with some Cairo related issue. Tried to solve it with all recommendations I could find here, on StackOverflow and other sites. No luck.

```
ERROR:  Error installing cairo:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.7.0/gems/cairo-1.16.6/ext/cairo
/usr/bin/ruby2.7 -I /usr/lib/ruby/2.7.0 -r ./siteconf20201101-1970-17vyn87.rb extconf.rb
checking for GCC... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```

Then I changed my mind and did infect my Windows with the Ruby devkit you recommended. Cairo failed again, but with another error. Quickly decided to uninstall the whole thing instead, so I cannot show you logs. I don't want to run your thing natively on Windows anyway.

Then I searched for a Docker version I was happy to see that you thought of Docker users as well. It's pretty cool, but it doesn't work either. The Ruby running inside the Docker image cannot find Squib. Not cool.

```
/usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- squib (LoadError)
        from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from deck.rb:1:in `<main>'
```

So, while as a fellow developer I appreciate the hard work you put into this thing, I still don't get why is it so damn hard to run. Please update the installing guidelines, do an FAQ, get rid of your unstable dependencies, because in its current state Squib doesn't rock at all. :(

**Comment by andymeneely** [comment]
I'll take a look at this. It does work on lots of peoples' machines - rest assured. Windows and Ruby don't always play nicely. I'm going back to some Squib work soon so I'll try to get some answers. Sorry this was painful!

**Comment by andymeneely** [comment]
Have you checked out the conversation in #326? Perhaps that will help
