### ISSUE TITLE
Cairo::InvalidMatrixError non-invertible matrix when using embedded icons

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#55]
If you're embedding icons into text, you may get this error:

```
 Cairo::InvalidMatrixError: invalid matrix (not invertible)
# ./vendor/bundle/ruby/2.0.0/gems/cairo-1.14.1/lib/cairo/context/rectangle.rb:20:in `move_to'
# ./vendor/bundle/ruby/2.0.0/gems/cairo-1.14.1/lib/cairo/context/rectangle.rb:20:in `rounded_rectangle'
# ./lib/squib/graphics/text.rb:16:in `draw_text_hint'
# ./lib/squib/graphics/text.rb:183:in `block in text'
# ./lib/squib/card.rb:51:in `yield'
# ./lib/squib/card.rb:51:in `use_cairo'
# ./lib/squib/graphics/text.rb:147:in `text'
# ./lib/squib/api/text.rb:50:in `block in text'
# ./lib/squib/api/text.rb:49:in `each'
# ./lib/squib/api/text.rb:49:in `text'
# ./samples/embed_text.rb:18:in `block in <top (required)>'
# ./lib/squib/deck.rb:80:in `instance_eval'
# ./lib/squib/deck.rb:80:in `initialize'
# ./samples/embed_text.rb:3:in `new'
 ./samples/embed_text.rb:3:in `<top (required)>'
```

This is a known issue that is platform-specific. It comes from the way we make the space to draw the icons on top of. In the `process_embeds` method we create three zero-sized characters with wide letter spacing. Some platforms are okay with this, others are not. We're still trying to separate out which is which.

If you had issues with this, please give us your:
  * OS
  * Squib version
  * Ruby version

**Comment by andymeneely** [comment]
This is also gone as of v0.11 because of the way I re-implemented image embedding.
