### ISSUE TITLE
Cairo::WriteError on save_sheet when columns are greater than cards

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#56]
Here's the reproducing case: 

```ruby
Squib::Deck.new(cards: 3) do
  text str: 'Hello'
  save_sheet prefix: 'bug_', columns: 4
end
```
Produces:
```
Cairo::WriteError: error while writing to output stream
C:/local/workspaces/ruby/squib/lib/squib/graphics/save_doc.rb:94:in `write_to_png'
C:/local/workspaces/ruby/squib/lib/squib/graphics/save_doc.rb:94:in `block (2 levels) in save_sheet'
C:/local/workspaces/ruby/squib/lib/squib/graphics/save_doc.rb:91:in `each'
C:/local/workspaces/ruby/squib/lib/squib/graphics/save_doc.rb:91:in `block in save_sheet'
C:/local/workspaces/ruby/squib/lib/squib/progress.rb:32:in `start'
C:/local/workspaces/ruby/squib/lib/squib/graphics/save_doc.rb:90:in `save_sheet'
embed_text.rb:94:in `block in <top (required)>'
C:/local/workspaces/ruby/squib/lib/squib/deck.rb:80:in `instance_eval'
C:/local/workspaces/ruby/squib/lib/squib/deck.rb:80:in `initialize'
embed_text.rb:92:in `new'
embed_text.rb:92:in `<top (required)>'
C:/local/workspaces/ruby/squib/Rakefile:16:in `load'
C:/local/workspaces/ruby/squib/Rakefile:16:in `block (2 levels) in <top (required)>'
C:/local/workspaces/ruby/squib/Rakefile:13:in `chdir'
C:/local/workspaces/ruby/squib/Rakefile:13:in `block in <top (required)>'
```
Changing to `columns: 3` makes this go away.

**Comment by andymeneely** [comment]
Not sure what's going on here. Going to the backlog since there's an easy workaround currently.
